name: Check Code Formatting (black)

on:
  pull_request:
    branches:
      - main

jobs:
  black-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Run black (check mode)
        run: |
          black --check .
