name: Deploy content to Pages

on:
  push:
    branches: [$default-branch]
  schedule:
    - cron: '26 * * * *'  # Hourly
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Scan the cast
        run: |
          ./zdenko.py https://dennikn.sk/slovensko/feed/ https://blsho.github.io/ncast/zdoma.png > output/zdoma.rss
          ./zdenko.py https://dennikn.sk/veda/feed https://blsho.github.io/ncast/zodbornik.png > output/zodbornik.rss
          ./zdenko.py https://dennikn.sk/kultura/feed https://blsho.github.io/ncast/zpapajogurt.png > output/zpapajogurt.rss
          ./zdenko.py https://dennikn.sk/sport/feed https://blsho.github.io/ncast/ztiper.png > output/ztiper.rss
          ./zdenko.py https://dennikn.sk/komentare/feed https://blsho.github.io/ncast/zvkrcme.png > output/zvkrcme.rss
          ./zdenko.py https://dennikn.sk/svet/feed https://blsho.github.io/ncast/zvonka.png > output/zvonka.rss
          ./zdenko.py https://dennikn.sk/ekonomika/feed https://blsho.github.io/ncast/zvpraci.png > output/zvpraci.rss
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4